query DonHangDetails($input: XemThongTinDonHangChoQuanLiInput!) {
  xemThongTinDonHangChoQuanLi(input: $input) {
    ok
    error {
      mainReason
      message
    }
    DonHang {
      ...DonHangFragment
    }
  }
}
