query SanPhamDetails($input: XemThongTinSanPhamInput!) {
  xemThongTinSanPham(input: $input) {
    ok
    error {
      mainReason
      message
    }
    sanpham {
      ...SanPhamFragment
    }
  }
}
