query DanhSachVoucher($input: XemDanhSachMaGiamGiaInput!) {
  xemDanhSachMaGiamGia(input: $input) {
    ok
    error {
      mainReason
      message
    }
    maGiamGias {
      ...VoucherFragment
    }
  }
}
