query DanhSachSanPham($input: XemDanhSachSanPhamInput!) {
  xemDanhSachSanPham(input: $input) {
    ok
    error {
      mainReason
      message
    }
    sanPhams {
      ...SanPhamFragment
    }
  }
}
